'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';

const faqs = [
  {
    question: 'Who can participate? 🎓',
    answer:
      'Any student from our college can participate. You just need to register with your college email and register number. All departments and years are welcome!',
  },
  {
    question: 'What topics are covered? 📚',
    answer:
      'Questions span across electronics fundamentals, circuit analysis, digital electronics, analog circuits, semiconductor devices, signals & systems, and embedded systems. Each round focuses on different difficulty levels.',
  },
  {
    question: 'How are rounds structured? 🏆',
    answer:
      'There are 3 rounds: Spark (basics with MCQ & True/False), Circuit (intermediate with Fill Blanks & Numerical), and Nexus (advanced with all question types). You must be promoted from the previous round to advance.',
  },
  {
    question: 'What happens if I switch tabs? 👁️',
    answer:
      'Our anti-cheat system detects tab switches, window blur, and fullscreen exits. Any violation results in immediate disqualification. Your attempt is automatically submitted and marked accordingly.',
  },
  {
    question: 'Can I retake a round? 🔄',
    answer:
      'No. Each participant gets exactly one attempt per round. Once you start, you must complete it within the time limit. There are no retakes or second chances.',
  },
  {
    question: 'How do certificates work? 📜',
    answer:
      'Certificates are generated by the admin for top performers after each round. You can download your certificate as a PDF from your participant dashboard once it\'s been issued.',
  },
];

export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="py-24 px-4 relative">
      <div className="max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="font-[family-name:var(--font-heading)] text-4xl md:text-5xl font-bold text-[var(--text)] mb-4">
            Got Questions? 🤔
          </h2>
          <p className="text-[var(--muted)] text-lg">
            Everything you need to know before diving in.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="space-y-3"
        >
          {faqs.map((faq, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
              className="rounded-xl overflow-hidden"
              style={{
                background: 'rgba(12, 20, 40, 0.7)',
                border: '1px solid rgba(0, 207, 255, 0.1)',
              }}
            >
              <button
                onClick={() => setOpenIndex(openIndex === i ? null : i)}
                className="w-full flex items-center justify-between p-5 text-left hover:bg-[rgba(0,207,255,0.05)] transition-colors duration-200"
              >
                <span className="font-semibold text-[var(--text)] text-lg pr-4">
                  {faq.question}
                </span>
                <motion.div
                  animate={{ rotate: openIndex === i ? 180 : 0 }}
                  transition={{ duration: 0.3 }}
                >
                  <ChevronDown size={20} className="text-[var(--primary)] flex-shrink-0" />
                </motion.div>
              </button>

              <AnimatePresence>
                {openIndex === i && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3, ease: 'easeInOut' }}
                    className="overflow-hidden"
                  >
                    <div className="px-5 pb-5 text-[var(--muted)] leading-relaxed">
                      {faq.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
