'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ArrowRight, Menu, X, Trophy,
  ShieldCheck, Activity, Sparkles, HelpCircle,
  Clock, Award, Gift, Rocket, Users, BookOpen,
  ChevronDown, Lock, User
} from 'lucide-react';
import Logo from '@/components/shared/Logo';
import GalaxyButton from '@/components/shared/GalaxyButton';
import GlassCard from '@/components/shared/GlassCard';
import FadeIn from '@/components/shared/FadeIn';
import CountUp from '@/components/shared/CountUp';

export default function HomePage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  // Countdown timer
  const [timeLeft, setTimeLeft] = useState({ days: '05', hours: '18', minutes: '42', seconds: '09' });

  // FAQ accordion state
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useEffect(() => {
    const targetDate = new Date();
    targetDate.setDate(targetDate.getDate() + 5);
    targetDate.setHours(targetDate.getHours() + 18);
    targetDate.setMinutes(targetDate.getMinutes() + 42);

    const interval = setInterval(() => {
      const now = new Date().getTime();
      const diff = targetDate.getTime() - now;
      if (diff <= 0) { clearInterval(interval); return; }
      const d = Math.floor(diff / (1000 * 60 * 60 * 24));
      const h = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      const m = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
      const s = Math.floor((diff % (1000 * 60)) / 1000);
      setTimeLeft({
        days: String(d).padStart(2, '0'),
        hours: String(h).padStart(2, '0'),
        minutes: String(m).padStart(2, '0'),
        seconds: String(s).padStart(2, '0'),
      });
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  const navLinks = [
    { label: 'Rounds', href: '#rounds' },
    { label: 'Rules', href: '#rules' },
    { label: 'FAQ', href: '#faq' },
  ];

  const faqItems = [
    { q: 'Who can participate?', a: 'Any student registered with a valid college ID from engineering, science, or technology departments can join the competition.' },
    { q: 'What topics are covered in each round?', a: 'Topics span electronics, circuits, digital systems, embedded systems, signal processing, and general engineering.' },
    { q: 'How does promotion between rounds work?', a: 'Top-scoring participants from each round are promoted to the next round by the admin based on live leaderboard rankings.' },
    { q: 'What happens if I switch tabs during a test?', a: 'Any tab switch, window blur, or fullscreen exit triggers immediate and permanent disqualification. There are no second chances.' },
    { q: 'Can I retake a round?', a: 'No. Once you start a round, you have one attempt. The timer cannot be paused.' },
    { q: 'How are certificates generated?', a: 'Digital certificates are generated by the admin after competition results are finalized and distributed via the portal.' },
  ];

  return (
    <div className="relative min-h-screen text-[var(--text-primary)] overflow-x-hidden">

      {/* ═══ NAVBAR ═══ */}
      <nav className="fixed top-0 left-0 right-0 z-50">
        <div className="mx-4 mt-3">
          <GlassCard variant="elevated" radius={16} hover={false} noHover className="!p-0 px-6 py-3">
            <div className="flex items-center justify-between max-w-7xl mx-auto gap-4 md:gap-8">
              <Link href="/" className="flex-shrink-0 mr-4">
                <Logo size="sm" />
              </Link>

              {/* Center Nav Links */}
              <div className="hidden lg:flex items-center justify-center gap-8 flex-1 mx-6">
                {navLinks.map((link) => (
                  <a
                    key={link.href}
                    href={link.href}
                    className="font-[family-name:var(--font-heading)] text-sm font-medium text-[var(--text-secondary)] hover:text-[#FFFFFF] transition-colors whitespace-nowrap px-2"
                  >
                    {link.label}
                  </a>
                ))}
              </div>

              {/* Right Action Buttons */}
              <div className="hidden lg:flex items-center gap-6 flex-shrink-0 ml-4">
                <Link href="/admin/login" className="font-[family-name:var(--font-body)] text-xs text-[#94A3B8] hover:text-[#FFFFFF] transition-colors font-light whitespace-nowrap px-1">
                  Admin
                </Link>
                <Link href="/quiz" className="flex-shrink-0">
                  <GalaxyButton variant="primary" size="sm" className="whitespace-nowrap">
                    Enter Quiz →
                  </GalaxyButton>
                </Link>
              </div>

              {/* Mobile Menu Trigger */}
              <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="lg:hidden p-2 text-[var(--text-secondary)]">
                {mobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
              </button>
            </div>
          </GlassCard>
        </div>

        {/* Mobile Dropdown */}
        <AnimatePresence>
          {mobileMenuOpen && (
            <motion.div
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="mx-4 mt-2 p-6 rounded-2xl flex flex-col gap-4 lg:hidden"
              style={{ background: 'rgba(10,1,24,0.95)', backdropFilter: 'blur(24px)', border: '1px solid var(--glass-border)' }}
            >
              {navLinks.map((link) => (
                <a
                  key={link.href}
                  href={link.href}
                  onClick={() => setMobileMenuOpen(false)}
                  className="font-[family-name:var(--font-heading)] text-base font-medium text-[var(--text-secondary)]"
                >
                  {link.label}
                </a>
              ))}
              <div className="flex flex-col gap-2 mt-2">
                <Link href="/quiz" onClick={() => setMobileMenuOpen(false)}>
                  <GalaxyButton variant="cyan" size="md" fullWidth>
                    Enter Quiz Now →
                  </GalaxyButton>
                </Link>
                <Link href="/admin/login" onClick={() => setMobileMenuOpen(false)}>
                  <GalaxyButton variant="secondary" size="md" fullWidth className="text-[var(--text-muted)]">
                    <ShieldCheck size={14} className="text-[var(--aurora-purple)]" />
                    Admin Login
                  </GalaxyButton>
                </Link>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </nav>

      {/* ═══ HERO SECTION ═══ */}
      <header className="relative z-10 pt-36 pb-20 min-h-[85vh] flex flex-col justify-center items-center text-center px-6">
        <div className="max-w-4xl mx-auto flex flex-col items-center gap-6">

          <FadeIn delay={0.1} y={30}>
            <h1 className="font-[family-name:var(--font-display)] font-extrabold tracking-tight leading-[1.05] text-[clamp(2.8rem,7vw,5.5rem)]">
              <span className="block text-[#FFFFFF]">Electronic Club</span>
              <span className="block text-[#FFFFFF] mt-1">Quiz Portal</span>
            </h1>
          </FadeIn>

          <FadeIn delay={0.25} y={20}>
            <p className="font-[family-name:var(--font-body)] font-light text-lg sm:text-xl text-[var(--text-muted)] max-w-2xl leading-relaxed">
              The premier national electronics championship. Three brutal rounds. Test your engineering mind and claim the trophy.
            </p>
          </FadeIn>

          {/* SINGLE HERO CTA BUTTON LINKING TO /quiz */}
          <FadeIn delay={0.35} y={20}>
            <div className="pt-4">
              <Link href="/quiz">
                <GalaxyButton variant="cyan" size="lg" className="!px-12 !py-4 text-base font-[family-name:var(--font-heading)] uppercase tracking-wider font-semibold">
                  Enter Quiz Now →
                </GalaxyButton>
              </Link>
            </div>
          </FadeIn>

        </div>

        {/* Scroll indicator */}
        <div className="mt-16">
          <motion.div animate={{ y: [0, 8, 0] }} transition={{ duration: 2, repeat: Infinity }}>
            <ChevronDown size={24} className="text-[var(--aurora-purple)] opacity-50" />
          </motion.div>
        </div>
      </header>

      {/* ═══ THE ROUNDS ═══ */}
      <section id="rounds" className="relative z-10 w-full scroll-mt-24 py-28" style={{ background: 'rgba(18, 8, 40, 0.8)' }}>
        <div className="max-w-7xl mx-auto px-6">
          <FadeIn>
            <div className="text-center mb-16">
              <span className="font-[family-name:var(--font-heading)] text-xs font-medium text-[var(--aurora-purple)] tracking-widest uppercase">✦ Competition</span>
              <h2 className="font-[family-name:var(--font-display)] text-[clamp(2rem,6vw,4.5rem)] font-extrabold gradient-text mt-2">The Rounds</h2>
            </div>
          </FadeIn>

          <div className="space-y-8">
            {[
              { num: '01', title: 'Qualifier Round', desc: 'Open for all registered participants. MCQ-based test covering fundamentals of electronics, circuits, and digital systems.', tags: ['MCQ', '30 min', 'Open to All'], color: 'var(--aurora-purple)', status: 'OPEN FOR ALL' },
              { num: '02', title: 'Advanced Round', desc: 'Promoted participants tackle mixed question types — MCQ, True/False, Fill-in-the-blank — with negative marking.', tags: ['Mixed', '45 min', 'Promoted'], color: 'var(--aurora-pink)', status: 'PROMOTION REQUIRED' },
              { num: '03', title: 'Grand Finale', desc: 'The ultimate challenge. Numerical and analytical questions. The top scorer becomes the champion.', tags: ['Numerical', '60 min', 'Elite'], color: 'var(--aurora-gold)', status: 'ELITE ONLY' },
            ].map((round, i) => (
              <FadeIn key={i} delay={i * 0.15}>
                <GlassCard variant="elevated" className="!p-10 relative overflow-hidden">
                  <div className="absolute top-4 right-8 font-[family-name:var(--font-mono)] font-black text-[8rem] leading-none gradient-text opacity-[0.06] select-none pointer-events-none">{round.num}</div>
                  <div className="relative z-10">
                    <div className="flex items-center gap-3 mb-4">
                      <span className="font-[family-name:var(--font-mono)] text-sm font-medium text-[var(--text-dim)]">ROUND {round.num}</span>
                      <span className="font-[family-name:var(--font-heading)] text-[10px] font-medium px-3 py-1 rounded-full tracking-wide" style={{ background: `${round.color}20`, color: round.color, border: `1px solid ${round.color}40` }}>{round.status}</span>
                    </div>
                    <h3 className="font-[family-name:var(--font-display)] text-2xl font-bold text-[var(--text-primary)] mb-3">{round.title}</h3>
                    <p className="font-[family-name:var(--font-body)] text-[var(--text-muted)] text-sm max-w-xl leading-relaxed mb-4">{round.desc}</p>
                    <div className="flex flex-wrap gap-2">
                      {round.tags.map(tag => (
                        <span key={tag} className="px-3 py-1 rounded-full text-xs font-[family-name:var(--font-heading)] font-medium" style={{ background: 'var(--glass-white)', border: '1px solid var(--glass-border)', color: 'var(--text-secondary)' }}>{tag}</span>
                      ))}
                    </div>
                  </div>
                </GlassCard>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ SECURITY / RULES ═══ */}
      <section id="rules" className="relative z-10 w-full max-w-7xl mx-auto px-6 py-24 scroll-mt-24">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-5">
            <FadeIn>
              <span className="font-[family-name:var(--font-heading)] text-xs font-medium text-[var(--aurora-rose)] tracking-widest uppercase">🔒 Security</span>
              <h2 className="font-[family-name:var(--font-display)] text-3xl font-extrabold text-[var(--text-primary)] mt-2 leading-tight">Zero Tolerance<br />Security ✦</h2>
              <p className="font-[family-name:var(--font-body)] text-[var(--text-muted)] text-sm mt-4 leading-relaxed max-w-sm">
                Our live proctoring system ensures competitive fairness across all rounds. Any violation triggers instant disqualification.
              </p>
              <Link href="/rules" className="inline-block mt-6"><GalaxyButton variant="secondary" size="md">Read Full Rules</GalaxyButton></Link>
            </FadeIn>
          </div>
          <div className="lg:col-span-7 grid grid-cols-1 sm:grid-cols-2 gap-4">
            {[
              { title: 'Fullscreen Lock', desc: 'Exiting fullscreen triggers instant flag.', icon: ShieldCheck },
              { title: 'Tab Detection', desc: 'Tab switches auto-disqualify.', icon: Activity },
              { title: 'Server Timer', desc: 'Timer runs on server — no tampering.', icon: Clock },
              { title: 'No Copy-Paste', desc: 'Clipboard and shortcuts blocked.', icon: Lock },
              { title: 'Randomized Qs', desc: 'Questions and options shuffled.', icon: BookOpen },
              { title: 'Proctor Logs', desc: 'All events logged server-side.', icon: Users },
            ].map((rule, i) => (
              <FadeIn key={i} delay={i * 0.08}>
                <GlassCard variant="purple" className="!p-5">
                  <rule.icon size={20} className="text-[var(--aurora-purple)] mb-3" />
                  <h4 className="font-[family-name:var(--font-heading)] font-medium text-[var(--text-primary)] text-sm mb-1">{rule.title}</h4>
                  <p className="font-[family-name:var(--font-body)] text-[var(--text-muted)] text-xs leading-relaxed">{rule.desc}</p>
                </GlassCard>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ BENEFITS ═══ */}
      <section className="relative z-10 w-full max-w-7xl mx-auto px-6 py-24">
        <FadeIn>
          <div className="text-center mb-16">
            <span className="font-[family-name:var(--font-heading)] text-xs font-medium text-[var(--aurora-purple)] tracking-widest uppercase">✦ Why Participate</span>
            <h2 className="font-[family-name:var(--font-display)] text-[clamp(2rem,6vw,4rem)] font-extrabold gradient-text mt-2">Win Glory ✦</h2>
          </div>
        </FadeIn>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {[
            { icon: Award, title: 'Certificates', desc: 'Official digital certificates for all participants.' },
            { icon: Gift, title: 'Cash Prizes', desc: 'Cash rewards and trophies for top performers.' },
            { icon: Rocket, title: 'Skill Growth', desc: 'Test your engineering knowledge under pressure.' },
            { icon: Users, title: 'Networking', desc: 'Connect with top minds from across colleges.' },
          ].map((b, i) => (
            <FadeIn key={i} delay={i * 0.1}>
              <GlassCard variant="elevated" className="!p-8 text-center flex flex-col items-center gap-4">
                <div className="w-14 h-14 rounded-2xl flex items-center justify-center" style={{ background: 'var(--glass-purple)', border: '1px solid rgba(168,85,247,0.25)' }}>
                  <b.icon size={24} className="text-[var(--aurora-purple)]" />
                </div>
                <h4 className="font-[family-name:var(--font-heading)] font-medium text-[var(--text-primary)] text-lg">{b.title}</h4>
                <p className="font-[family-name:var(--font-body)] text-[var(--text-muted)] text-xs leading-relaxed">{b.desc}</p>
              </GlassCard>
            </FadeIn>
          ))}
        </div>
      </section>

      {/* ═══ FAQ ═══ */}
      <section id="faq" className="relative z-10 w-full scroll-mt-24 py-24" style={{ background: 'var(--space-surface)' }}>
        <div className="max-w-4xl mx-auto px-6">
          <FadeIn>
            <div className="text-center mb-16">
              <span className="font-[family-name:var(--font-heading)] text-xs font-medium text-[var(--aurora-purple)] tracking-widest uppercase"><HelpCircle size={12} className="inline mr-1" /> FAQ</span>
              <h2 className="font-[family-name:var(--font-display)] text-[clamp(2rem,6vw,4rem)] font-extrabold gradient-text mt-2">Questions? ✦</h2>
            </div>
          </FadeIn>
          <div className="space-y-4">
            {faqItems.map((item, i) => (
              <FadeIn key={i} delay={i * 0.08}>
                <GlassCard variant="elevated" hover={false} noHover className="!p-0 overflow-hidden cursor-pointer" onClick={() => setOpenFaq(openFaq === i ? null : i)}>
                  <div className="px-7 py-5 flex items-center justify-between">
                    <h4 className="font-[family-name:var(--font-heading)] font-medium text-[var(--text-primary)] text-sm">{item.q}</h4>
                    <motion.span animate={{ rotate: openFaq === i ? 45 : 0 }} className="text-[var(--aurora-purple)] text-xl font-light">+</motion.span>
                  </div>
                  <AnimatePresence>
                    {openFaq === i && (
                      <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.3 }}>
                        <div className="px-7 pb-5 border-t border-[rgba(168,85,247,0.15)]">
                          <p className="font-[family-name:var(--font-body)] text-[var(--text-muted)] text-sm leading-relaxed pt-4">{item.a}</p>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </GlassCard>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ CTA BANNER ═══ */}
      <section className="relative z-10 w-full max-w-7xl mx-auto px-6 py-24">
        <FadeIn>
          <GlassCard variant="elevated" className="!p-16 text-center relative overflow-hidden" radius={32}>
            <div className="absolute inset-0 pointer-events-none" style={{ background: 'radial-gradient(ellipse at center, rgba(124,58,237,0.2) 0%, transparent 70%)' }} />
            <div className="relative z-10">
              <h2 className="font-[family-name:var(--font-display)] text-[clamp(1.5rem,5vw,3.5rem)] font-extrabold text-[#FFFFFF] mb-6">
                Ready to Prove Your Skills?
              </h2>
              <Link href="/quiz">
                <GalaxyButton variant="cyan" size="lg">Enter Quiz Now →</GalaxyButton>
              </Link>
            </div>
          </GlassCard>
        </FadeIn>
      </section>

      {/* ═══ FOOTER ═══ */}
      <footer className="relative z-10 border-t border-[var(--glass-border)]" style={{ background: 'var(--space-deep)' }}>
        <div className="max-w-7xl mx-auto px-6 py-12 flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex flex-col items-center md:items-start">
            <Logo size="sm" />
            <p className="font-[family-name:var(--font-body)] text-[var(--text-dim)] text-xs mt-2">National Level Quiz Championship Portal</p>
          </div>
          <div className="flex flex-wrap justify-center gap-6 text-xs font-[family-name:var(--font-heading)] text-[var(--text-muted)]">
            <a href="#about" className="hover:text-[var(--aurora-purple)]">About</a>
            <a href="#rounds" className="hover:text-[var(--aurora-purple)]">Rounds</a>
            <a href="#rules" className="hover:text-[var(--aurora-purple)]">Rules</a>
            <a href="#faq" className="hover:text-[var(--aurora-purple)]">FAQ</a>
            <Link href="/quiz" className="hover:text-[var(--aurora-cyan)]">Enter Quiz</Link>
            <Link href="/admin/login" className="hover:text-[var(--aurora-rose)] text-[var(--text-dim)]">Admin →</Link>
          </div>
        </div>
        <div className="text-center py-6 border-t border-[var(--glass-border)]">
          <p className="font-[family-name:var(--font-body)] text-[var(--text-dim)] text-[10px] tracking-widest uppercase">
            © {new Date().getFullYear()} Electronic Club ⚡ Quiz Portal · All Rights Reserved
          </p>
        </div>
      </footer>
    </div>
  );
}
